
var __cov_p5pZsAMiMpUczRxpMo2qBw = (Function('return this'))();
if (!__cov_p5pZsAMiMpUczRxpMo2qBw.__coverage__) { __cov_p5pZsAMiMpUczRxpMo2qBw.__coverage__ = {}; }
__cov_p5pZsAMiMpUczRxpMo2qBw = __cov_p5pZsAMiMpUczRxpMo2qBw.__coverage__;
if (!(__cov_p5pZsAMiMpUczRxpMo2qBw['assests/js/custom.js'])) {
   __cov_p5pZsAMiMpUczRxpMo2qBw['assests/js/custom.js'] = {"path":"assests/js/custom.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0},"b":{"1":[0,0],"2":[0,0],"3":[0,0],"4":[0,0]},"f":{"1":0},"fnMap":{"1":{"name":"(anonymous_1)","line":23,"loc":{"start":{"line":23,"column":2},"end":{"line":23,"column":14}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":94}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":94}},"3":{"start":{"line":3,"column":0},"end":{"line":3,"column":90}},"4":{"start":{"line":5,"column":0},"end":{"line":13,"column":1}},"5":{"start":{"line":6,"column":2},"end":{"line":8,"column":5}},"6":{"start":{"line":7,"column":4},"end":{"line":7,"column":47}},"7":{"start":{"line":10,"column":2},"end":{"line":12,"column":4}},"8":{"start":{"line":11,"column":4},"end":{"line":11,"column":36}},"9":{"start":{"line":15,"column":0},"end":{"line":21,"column":3}},"10":{"start":{"line":23,"column":0},"end":{"line":38,"column":3}},"11":{"start":{"line":24,"column":2},"end":{"line":37,"column":5}}},"branchMap":{"1":{"line":1,"type":"cond-expr","locations":[{"start":{"line":1,"column":51},"end":{"line":1,"column":60}},{"start":{"line":1,"column":63},"end":{"line":1,"column":93}}]},"2":{"line":2,"type":"cond-expr","locations":[{"start":{"line":2,"column":51},"end":{"line":2,"column":60}},{"start":{"line":2,"column":63},"end":{"line":2,"column":93}}]},"3":{"line":3,"type":"cond-expr","locations":[{"start":{"line":3,"column":65},"end":{"line":3,"column":81}},{"start":{"line":3,"column":84},"end":{"line":3,"column":89}}]},"4":{"line":5,"type":"if","locations":[{"start":{"line":5,"column":0},"end":{"line":5,"column":0}},{"start":{"line":5,"column":0},"end":{"line":5,"column":0}}]}}};
}
__cov_p5pZsAMiMpUczRxpMo2qBw = __cov_p5pZsAMiMpUczRxpMo2qBw['assests/js/custom.js'];
__cov_p5pZsAMiMpUczRxpMo2qBw.s['1']++;var r_uploadURL=typeof uploadURL!=='undefined'?(__cov_p5pZsAMiMpUczRxpMo2qBw.b['1'][0]++,uploadURL):(__cov_p5pZsAMiMpUczRxpMo2qBw.b['1'][1]++,'http://localhost:3000/upload');__cov_p5pZsAMiMpUczRxpMo2qBw.s['2']++;var r_deleteURL=typeof deleteURL!=='undefined'?(__cov_p5pZsAMiMpUczRxpMo2qBw.b['2'][0]++,deleteURL):(__cov_p5pZsAMiMpUczRxpMo2qBw.b['2'][1]++,'http://localhost:3000/delete');__cov_p5pZsAMiMpUczRxpMo2qBw.s['3']++;var r_admin_permission=typeof admin_permission!=='undefined'?(__cov_p5pZsAMiMpUczRxpMo2qBw.b['3'][0]++,admin_permission):(__cov_p5pZsAMiMpUczRxpMo2qBw.b['3'][1]++,false);__cov_p5pZsAMiMpUczRxpMo2qBw.s['4']++;if(!r_admin_permission){__cov_p5pZsAMiMpUczRxpMo2qBw.b['4'][0]++;__cov_p5pZsAMiMpUczRxpMo2qBw.s['5']++;document.querySelectorAll('figcaption').forEach(element=>{__cov_p5pZsAMiMpUczRxpMo2qBw.s['6']++;element.removeAttribute('contenteditable');});__cov_p5pZsAMiMpUczRxpMo2qBw.s['7']++;document.querySelectorAll('editable').forEach(element=>{__cov_p5pZsAMiMpUczRxpMo2qBw.s['8']++;element.removeClass('editable');});}else{__cov_p5pZsAMiMpUczRxpMo2qBw.b['4'][1]++;}__cov_p5pZsAMiMpUczRxpMo2qBw.s['9']++;var editor=new MediumEditor('.editable',{buttonLabels:'fontawesome',paste:{cleanPastedHTML:true,forcePlainText:false}});__cov_p5pZsAMiMpUczRxpMo2qBw.s['10']++;$(function(){__cov_p5pZsAMiMpUczRxpMo2qBw.f['1']++;__cov_p5pZsAMiMpUczRxpMo2qBw.s['11']++;$('.editable').mediumInsert({editor:editor,enabled:r_admin_permission,addons:{images:{fileDeleteOptions:{url:r_deleteURL},fileUploadOptions:{url:r_uploadURL}}}});});
