
var __cov_PadPgZ3bzrHvy3_NdVOqjg = (Function('return this'))();
if (!__cov_PadPgZ3bzrHvy3_NdVOqjg.__coverage__) { __cov_PadPgZ3bzrHvy3_NdVOqjg.__coverage__ = {}; }
__cov_PadPgZ3bzrHvy3_NdVOqjg = __cov_PadPgZ3bzrHvy3_NdVOqjg.__coverage__;
if (!(__cov_PadPgZ3bzrHvy3_NdVOqjg['src/js/version.js'])) {
   __cov_PadPgZ3bzrHvy3_NdVOqjg['src/js/version.js'] = {"path":"src/js/version.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0},"b":{"1":[0,0],"2":[0,0]},"f":{"1":0,"2":0},"fnMap":{"1":{"name":"(anonymous_1)","line":1,"loc":{"start":{"line":1,"column":34},"end":{"line":1,"column":53}}},"2":{"name":"(anonymous_2)","line":10,"loc":{"start":{"line":10,"column":18},"end":{"line":10,"column":30}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":14,"column":2}},"2":{"start":{"line":2,"column":4},"end":{"line":4,"column":56}},"3":{"start":{"line":5,"column":4},"end":{"line":13,"column":6}},"4":{"start":{"line":11,"column":12},"end":{"line":11,"column":105}},"5":{"start":{"line":16,"column":0},"end":{"line":19,"column":12}}},"branchMap":{"1":{"line":4,"type":"cond-expr","locations":[{"start":{"line":4,"column":42},"end":{"line":4,"column":50}},{"start":{"line":4,"column":53},"end":{"line":4,"column":55}}]},"2":{"line":11,"type":"cond-expr","locations":[{"start":{"line":11,"column":82},"end":{"line":11,"column":98}},{"start":{"line":11,"column":101},"end":{"line":11,"column":103}}]}}};
}
__cov_PadPgZ3bzrHvy3_NdVOqjg = __cov_PadPgZ3bzrHvy3_NdVOqjg['src/js/version.js'];
__cov_PadPgZ3bzrHvy3_NdVOqjg.s['1']++;MediumEditor.parseVersionString=function(release){__cov_PadPgZ3bzrHvy3_NdVOqjg.f['1']++;__cov_PadPgZ3bzrHvy3_NdVOqjg.s['2']++;var split=release.split('-'),version=split[0].split('.'),preRelease=split.length>1?(__cov_PadPgZ3bzrHvy3_NdVOqjg.b['1'][0]++,split[1]):(__cov_PadPgZ3bzrHvy3_NdVOqjg.b['1'][1]++,'');__cov_PadPgZ3bzrHvy3_NdVOqjg.s['3']++;return{major:parseInt(version[0],10),minor:parseInt(version[1],10),revision:parseInt(version[2],10),preRelease:preRelease,toString:function(){__cov_PadPgZ3bzrHvy3_NdVOqjg.f['2']++;__cov_PadPgZ3bzrHvy3_NdVOqjg.s['4']++;return[version[0],version[1],version[2]].join('.')+(preRelease?(__cov_PadPgZ3bzrHvy3_NdVOqjg.b['2'][0]++,'-'+preRelease):(__cov_PadPgZ3bzrHvy3_NdVOqjg.b['2'][1]++,''));}};};__cov_PadPgZ3bzrHvy3_NdVOqjg.s['5']++;MediumEditor.version=MediumEditor.parseVersionString.call(this,{'version':'6.0.0'}.version);
